### ISSUE TITLE
Document how to configure oci registry without docker config in 'getting started'

### ISSUE THREAD

**Issue by fwilhe** [open-component-model/ocm-website#205]
**What would you like to be added**:

I think [this page](https://ocm.software/docs/guides/getting-started-with-ocm/#prerequisites) could use a hint for how to configure an oci registry without docker config. It could either be directly added to this page, or link to a description. I could not find a good description of the config format.

**Why is this needed**:

In some cases, installing docker is not desired or allowed.

I was playing around with a local oci registry and with github package registry. I think describing how they can be configured without relying on docker would be good.

**Comment by morri-son** [comment]
Hi @fwilhe , we restructured (or better: still do :-)) our website. We moved the getting started guide. Once the [PR](https://github.com/open-component-model/ocm-website/pull/239) has been merged, you should find what you're requested in this issue here: https://ocm.software/docs/getting-started/first-steps-with-ocm/#using-basic-authentication
